apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloth
  template:
    metadata:
      labels:
        app: cloth
    spec:
      containers:
        - name: cloth
          image: fujinugraha/cloth
          env:
            - name: MONGO_URI
              value: "mongodb://cloth-mongo-clusterip-srv:27017/cloth"
            - name: NATS_CLUSTER_ID
              value: "microservice-event-driven"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-clusterip-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: cloth-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: cloth
  ports:
    - name: cloth
      protocol: TCP
      port: 3000
      targetPort: 3000
