apiVersion: apps/v1
kind: Deployment
metadata:
  name: sale-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sale
  template:
    metadata:
      labels:
        app: sale
    spec:
      containers:
        - name: sale
          image: fujinugraha/sale:event-driven
          env:
            - name: MONGO_URI
              value: "mongodb://sale-mongo-clusterip-srv:27017/sale"
            - name: NATS_CLUSTER_ID
              value: "event-driven"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-clusterip-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: sale-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: sale
  ports:
    - name: sale
      protocol: TCP
      port: 3000
      targetPort: 3000
