apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: fujinugraha/stock
          env:
            - name: MONGO_URI
              value: "mongodb://stock-mongo-clusterip-srv:27017/stock"
            - name: NATS_CLUSTER_ID
              value: "microservice-event-driven"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-clusterip-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: stock-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: stock
  ports:
    - name: stock
      protocol: TCP
      port: 3000
      targetPort: 3000
